name: KBS WORLD TV

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: config
        run: |
          git pull
          git config --global user.email "zaid.zer9@gmail.com"
          git config --global user.name "ZazerConer's"
      - name: Main
        run: |
          pwd
          chmod +x kbsworldtv.sh
          ./kbsworldtv.sh
      - name: git add
        run: |
          git add -A
          ls -la
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
